### Variáveis (Configure com seus dados reais)
@host = https://projeto-rag-15382c.es.us-central1.gcp.cloud.es.io
@api_key = enZQa3g1OEJtSjFheWRaR0FvR2g6bElaQXdoSG5BMUV0c0tuLV9ucF8wdw==

### 1. Teste a Conexão (Ping)
GET {{host}}
Authorization: ApiKey {{api_key}}

### 2. Verificar os índices existentes
GET {{host}}/_cat/indices?v
Authorization: ApiKey {{api_key}}

### 3. Deletar o Índice Atual (CUIDADO!)
DELETE {{host}}/projeto_rag_chunks
Authorization: ApiKey {{api_key}}

###4. Criando o modelo de embeddings
PUT {{host}}/_ingest/pipeline/ragflow_e5_pipeline
Authorization: ApiKey {{api_key}}
Content-Type: application/json

{
  "description": "Pipeline de ETL RAG de estudo -> E5-Small 384d Embeddings",
  "processors": [
    {
      "inference": {
        "model_id": ".multilingual-e5-small_linux-x86_64",
        "target_field": "chunk_vector",
        "field_map": {
          "text_content": "text_field"
        }
      }
    },
    {
      "set": {
        "field": "chunk_vector",
        "copy_from": "chunk_vector.predicted_value"
      }
    }
  ]
}

### 5. Criar o Índice com Mapping (Vetor) e Settings (Pipeline)
PUT {{host}}/projeto_rag_chunks
Authorization: ApiKey {{api_key}}
Content-Type: application/json

{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1,
    "index.default_pipeline": "ragflow_e5_pipeline",
    "routing.allocation.include._tier_preference": "data_content",
    "analysis": {
      "filter": {
        "brazilian_stemmer": {
          "type": "stemmer",
          "language": "brazilian"
        },
        "brazilian_stop": {
          "type": "stop",
          "stopwords": "brazilian"
        }
      },
      "analyzer": {
        "custom_br": {
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "brazilian_stop",
            "brazilian_stemmer"
          ]
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "chunk_id": { "type": "keyword" },
      "document_id": { "type": "keyword" },
      "text_content": { "type": "text", "analyzer": "custom_br" },
      "chunk_vector": {
        "type": "dense_vector",
        "dims": 384,
        "index": true,
        "similarity": "cosine",
        "index_options": {
          "type": "bbq_hnsw",
          "m": 16,
          "ef_construction": 100,
          "rescore_vector": { "oversample": 3 }
        }
      },
      "metadata": {
        "properties": {
          "source_file": { "type": "keyword" },
          "page_number": { "type": "integer" },
          "content_type": { "type": "keyword" }
        }
      }
    }
  }
}

### 5. Verificar se os documentos entraram (após rodar seu script Python)
GET {{host}}/projeto_rag_chunks/_search
Authorization: ApiKey {{api_key}}
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}

### 6.Verificando se funcionou
GET {{host}}/projeto_rag_chunks/_count
Authorization: ApiKey {{api_key}}


### 6.Verificando se funcionou
GET {{host}}/projeto_rag_chunks_v2/_search?size=1
Authorization: ApiKey {{api_key}}

### 7. Verificar a estrutura (Mapping) do índice
GET {{host}}/projeto_rag_chunks_v2/_mapping
Authorization: ApiKey {{api_key}}